import type { Quest, QuestProgress } from '@/src/features/quests/questProgress';
import { DEFAULT_PROFILE_ID } from '@/src/features/quests/questProgress';

export const quests: Quest[] = [
  {
    id: 'math-1',
    categoryId: 'math',
    title: '사과를 세어보자',
    level: 1,
    order: 1,
    introduction: '미어루와 사과를 하나씩 세어봐요.',
    reward: { id: 'math-star-1', title: '사과 별', type: 'star' },
    backgroundAsset: 'math-cave-background',
    visualLayout: 'apple-count',
    steps: [
      {
        id: 'math-1-step-1',
        type: 'choice',
        instructionText: '사과가 몇 개 있나요?',
        choices: [
          { id: 'two', label: '2개' },
          { id: 'three', label: '3개' },
        ],
        correctChoiceId: 'three',
        hintText: '손가락으로 사과를 하나씩 짚어봐요.',
        successMessage: '좋아, 하나씩 잘 세었어!',
      },
    ],
  },
  {
    id: 'math-2',
    categoryId: 'math',
    title: '동그라미를 찾아요',
    level: 2,
    order: 2,
    introduction: '수학 동굴 벽에서 둥근 모양을 찾아봐요.',
    reward: { id: 'math-star-2', title: '도형 별', type: 'star' },
    steps: [
      {
        id: 'math-2-step-1',
        type: 'choice',
        instructionText: '어떤 모양이 동그라미인가요?',
        choices: [
          { id: 'circle', label: '동그라미' },
          { id: 'square', label: '네모' },
          { id: 'triangle', label: '세모' },
        ],
        correctChoiceId: 'circle',
        hintText: '모서리가 없이 둥글게 이어진 모양을 찾아요.',
        successMessage: '맞아, 둥글둥글 동그라미야!',
      },
    ],
  },
  {
    id: 'math-3',
    categoryId: 'math',
    title: '패턴 길을 이어요',
    level: 3,
    order: 3,
    introduction: '반복되는 길을 보고 다음 그림을 골라요.',
    reward: { id: 'math-badge-3', title: '패턴 배지', type: 'badge' },
    steps: [
      {
        id: 'math-3-step-1',
        type: 'choice',
        instructionText: '빨강, 파랑, 빨강, 파랑 다음은 무엇일까요?',
        choices: [
          { id: 'red', label: '빨강' },
          { id: 'blue', label: '파랑' },
          { id: 'yellow', label: '노랑' },
        ],
        correctChoiceId: 'red',
        hintText: '처음부터 색을 천천히 말해봐요.',
        successMessage: '패턴 길을 멋지게 이었어!',
      },
    ],
  },
  {
    id: 'math-4',
    categoryId: 'math',
    title: '큰 바위를 골라요',
    level: 4,
    order: 4,
    introduction: '미어루가 지나갈 수 있게 더 큰 바위를 찾아요.',
    reward: { id: 'math-sticker-4', title: '큰 바위 스티커', type: 'sticker' },
    steps: [
      {
        id: 'math-4-step-1',
        type: 'choice',
        instructionText: '어떤 바위가 더 큰가요?',
        choices: [
          { id: 'small-rock', label: '작은 바위' },
          { id: 'big-rock', label: '큰 바위' },
          { id: 'leaf', label: '나뭇잎' },
        ],
        correctChoiceId: 'big-rock',
        hintText: '더 많은 자리를 차지하는 그림을 찾아봐요.',
        successMessage: '큰 것을 잘 비교했어!',
      },
    ],
  },
  {
    id: 'math-5',
    categoryId: 'math',
    title: '도전 숫자 문',
    level: 5,
    order: 5,
    introduction: '수학 동굴 마지막 문을 숫자로 열어봐요.',
    reward: { id: 'math-badge-5', title: '수학 동굴 배지', type: 'badge' },
    steps: [
      {
        id: 'math-5-step-1',
        type: 'choice',
        instructionText: '2개에 1개를 더하면 몇 개인가요?',
        choices: [
          { id: 'two', label: '2개' },
          { id: 'three', label: '3개' },
          { id: 'four', label: '4개' },
        ],
        correctChoiceId: 'three',
        hintText: '사과 2개에서 하나를 더 올려봐요.',
        successMessage: '수학 동굴 문이 활짝 열렸어!',
      },
    ],
  },
  {
    id: 'language-1',
    categoryId: 'language',
    title: '어떤 소리가 났을까',
    level: 1,
    order: 1,
    introduction: '소리를 듣고 알맞은 그림을 골라요.',
    reward: { id: 'language-star-1', title: '소리 별', type: 'star' },
    steps: [
      {
        id: 'language-1-step-1',
        type: 'choice',
        instructionText: '멍멍 소리는 어떤 친구의 소리인가요?',
        choices: [
          { id: 'dog', label: '강아지' },
          { id: 'cat', label: '고양이' },
        ],
        correctChoiceId: 'dog',
        hintText: '강아지가 인사할 때 나는 소리를 떠올려요.',
        successMessage: '소리와 그림을 잘 연결했어!',
      },
    ],
  },
  {
    id: 'language-2',
    categoryId: 'language',
    title: '그림 단어를 골라요',
    level: 2,
    order: 2,
    introduction: '그림을 보고 알맞은 단어를 찾아요.',
    reward: { id: 'language-star-2', title: '그림 단어 별', type: 'star' },
    steps: [
      {
        id: 'language-2-step-1',
        type: 'choice',
        instructionText: '빨간 과일 그림에 어울리는 단어는 무엇인가요?',
        choices: [
          { id: 'apple', label: '사과' },
          { id: 'shoe', label: '신발' },
          { id: 'cloud', label: '구름' },
        ],
        correctChoiceId: 'apple',
        hintText: '아삭아삭 먹는 빨간 과일이에요.',
        successMessage: '그림과 단어를 잘 찾았어!',
      },
    ],
  },
  {
    id: 'language-3',
    categoryId: 'language',
    title: '이야기 순서 맞추기',
    level: 3,
    order: 3,
    introduction: '짧은 이야기를 듣고 다음 장면을 골라요.',
    reward: { id: 'language-badge-3', title: '이야기 배지', type: 'badge' },
    steps: [
      {
        id: 'language-3-step-1',
        type: 'choice',
        instructionText: '씨앗을 심은 다음에는 무엇을 할까요?',
        choices: [
          { id: 'water', label: '물을 줘요' },
          { id: 'sleep', label: '잠을 자요' },
          { id: 'run', label: '달려요' },
        ],
        correctChoiceId: 'water',
        hintText: '식물이 자라려면 무엇이 필요할까요?',
        successMessage: '이야기 순서를 잘 이어줬어!',
      },
    ],
  },
  {
    id: 'language-4',
    categoryId: 'language',
    title: '감정을 말해요',
    level: 4,
    order: 4,
    introduction: '표정을 보고 감정을 말로 표현해요.',
    reward: { id: 'language-sticker-4', title: '감정 말풍선 스티커', type: 'sticker' },
    steps: [
      {
        id: 'language-4-step-1',
        type: 'choice',
        instructionText: '활짝 웃는 얼굴은 어떤 기분일까요?',
        choices: [
          { id: 'happy', label: '기뻐요' },
          { id: 'angry', label: '화나요' },
          { id: 'sleepy', label: '졸려요' },
        ],
        correctChoiceId: 'happy',
        hintText: '입꼬리가 올라가고 눈이 반짝여요.',
        successMessage: '기쁜 마음을 잘 말했어!',
      },
    ],
  },
  {
    id: 'language-5',
    categoryId: 'language',
    title: '도전 말 찾기',
    level: 5,
    order: 5,
    introduction: '상황에 어울리는 말을 스스로 골라요.',
    reward: { id: 'language-badge-5', title: '언어 언덕 배지', type: 'badge' },
    steps: [
      {
        id: 'language-5-step-1',
        type: 'choice',
        instructionText: '친구가 선물을 주면 어떤 말을 하면 좋을까요?',
        choices: [
          { id: 'thanks', label: '고마워' },
          { id: 'no', label: '싫어' },
          { id: 'bye', label: '잘 가' },
        ],
        correctChoiceId: 'thanks',
        hintText: '좋은 마음을 받았을 때 쓰는 말을 떠올려요.',
        successMessage: '상황에 맞는 말을 잘 골랐어!',
      },
    ],
  },
  {
    id: 'social-1',
    categoryId: 'social',
    title: '친구가 빌리고 싶대',
    level: 1,
    order: 1,
    introduction: '친구와 장난감을 나누는 방법을 배워요.',
    reward: { id: 'social-star-1', title: '나눔 별', type: 'star' },
    steps: [
      {
        id: 'social-1-step-1',
        type: 'choice',
        instructionText: '친구가 장난감을 빌리고 싶대요. 어떻게 말하면 좋을까요?',
        choices: [
          { id: 'share', label: '같이 쓰자' },
          { id: 'push', label: '밀쳐요' },
        ],
        correctChoiceId: 'share',
        hintText: '친구와 함께 즐겁게 노는 말을 찾아요.',
        successMessage: '친구 마음을 잘 생각했어!',
      },
    ],
  },
  {
    id: 'social-2',
    categoryId: 'social',
    title: '고마워를 말해요',
    level: 2,
    order: 2,
    introduction: '도움을 받았을 때 하는 말을 배워요.',
    reward: { id: 'social-star-2', title: '감사 별', type: 'star' },
    steps: [
      {
        id: 'social-2-step-1',
        type: 'choice',
        instructionText: '친구가 도와줬어요. 어떤 말을 하면 좋을까요?',
        choices: [
          { id: 'thanks', label: '고마워' },
          { id: 'angry', label: '화났어' },
          { id: 'hide', label: '숨을래' },
        ],
        correctChoiceId: 'thanks',
        hintText: '도움을 받았을 때 따뜻하게 하는 말이에요.',
        successMessage: '고마운 마음을 잘 표현했어!',
      },
    ],
  },
  {
    id: 'social-3',
    categoryId: 'social',
    title: '차례를 기다려요',
    level: 3,
    order: 3,
    introduction: '놀이터에서 차례를 기다리는 방법을 골라요.',
    reward: { id: 'social-badge-3', title: '기다림 배지', type: 'badge' },
    steps: [
      {
        id: 'social-3-step-1',
        type: 'choice',
        instructionText: '미끄럼틀 앞에 친구가 있어요. 어떻게 할까요?',
        choices: [
          { id: 'wait', label: '기다려요' },
          { id: 'cut', label: '앞으로 가요' },
          { id: 'shout', label: '소리쳐요' },
        ],
        correctChoiceId: 'wait',
        hintText: '모두가 즐겁게 놀 수 있는 행동을 찾아요.',
        successMessage: '차례를 멋지게 기다렸어!',
      },
    ],
  },
  {
    id: 'social-4',
    categoryId: 'social',
    title: '미안해를 전해요',
    level: 4,
    order: 4,
    introduction: '실수했을 때 마음을 전하는 말을 배워요.',
    reward: { id: 'social-sticker-4', title: '화해 스티커', type: 'sticker' },
    steps: [
      {
        id: 'social-4-step-1',
        type: 'choice',
        instructionText: '실수로 친구 블록을 무너뜨렸어요. 어떤 말을 할까요?',
        choices: [
          { id: 'sorry', label: '미안해' },
          { id: 'laugh', label: '웃어요' },
          { id: 'ignore', label: '모른 척해요' },
        ],
        correctChoiceId: 'sorry',
        hintText: '친구 마음을 생각하며 전하는 말을 골라요.',
        successMessage: '미안한 마음을 용기 있게 전했어!',
      },
    ],
  },
  {
    id: 'social-5',
    categoryId: 'social',
    title: '도전 마음 선택',
    level: 5,
    order: 5,
    introduction: '상황에 맞는 따뜻한 행동을 스스로 골라요.',
    reward: { id: 'social-badge-5', title: '마음 놀이터 배지', type: 'badge' },
    steps: [
      {
        id: 'social-5-step-1',
        type: 'choice',
        instructionText: '친구가 슬퍼 보여요. 어떤 행동이 좋을까요?',
        choices: [
          { id: 'comfort', label: '괜찮아? 하고 물어요' },
          { id: 'tease', label: '놀려요' },
          { id: 'leave', label: '그냥 가요' },
        ],
        correctChoiceId: 'comfort',
        hintText: '친구 마음을 살피는 행동을 찾아요.',
        successMessage: '친구를 다정하게 살폈어!',
      },
    ],
  },
  {
    id: 'safety-1',
    categoryId: 'safety',
    title: '횡단보도에서 멈춰요',
    level: 1,
    order: 1,
    introduction: '길을 건너기 전 멈추는 습관을 배워요.',
    reward: { id: 'safety-star-1', title: '멈춤 별', type: 'star' },
    steps: [
      {
        id: 'safety-1-step-1',
        type: 'choice',
        instructionText: '빨간불일 때는 어떻게 해야 할까요?',
        choices: [
          { id: 'stop', label: '멈춰요' },
          { id: 'run', label: '뛰어가요' },
        ],
        correctChoiceId: 'stop',
        hintText: '빨간불은 잠깐 기다리라는 신호예요.',
        successMessage: '안전하게 멈췄어!',
      },
    ],
  },
  {
    id: 'safety-2',
    categoryId: 'safety',
    title: '뜨거운 물건을 피해요',
    level: 2,
    order: 2,
    introduction: '뜨거운 물건을 만지지 않는 방법을 배워요.',
    reward: { id: 'safety-star-2', title: '조심 별', type: 'star' },
    steps: [
      {
        id: 'safety-2-step-1',
        type: 'choice',
        instructionText: '김이 나는 냄비를 보면 어떻게 해야 할까요?',
        choices: [
          { id: 'ask-adult', label: '어른에게 말해요' },
          { id: 'touch', label: '만져봐요' },
          { id: 'pull', label: '잡아당겨요' },
        ],
        correctChoiceId: 'ask-adult',
        hintText: '뜨거운 것은 어른과 함께 확인해요.',
        successMessage: '위험한 물건을 잘 알아차렸어!',
      },
    ],
  },
  {
    id: 'safety-3',
    categoryId: 'safety',
    title: '낯선 사람을 조심해요',
    level: 3,
    order: 3,
    introduction: '낯선 사람이 부를 때 안전한 행동을 골라요.',
    reward: { id: 'safety-badge-3', title: '안전 약속 배지', type: 'badge' },
    steps: [
      {
        id: 'safety-3-step-1',
        type: 'choice',
        instructionText: '모르는 사람이 같이 가자고 해요. 어떻게 할까요?',
        choices: [
          { id: 'tell-adult', label: '믿는 어른에게 말해요' },
          { id: 'follow', label: '따라가요' },
          { id: 'secret', label: '비밀로 해요' },
        ],
        correctChoiceId: 'tell-adult',
        hintText: '혼자 결정하지 않고 믿는 어른에게 알려요.',
        successMessage: '안전한 선택을 잘했어!',
      },
    ],
  },
  {
    id: 'safety-4',
    categoryId: 'safety',
    title: '불이 나면 대피해요',
    level: 4,
    order: 4,
    introduction: '불이 났을 때 밖으로 나가는 행동을 배워요.',
    reward: { id: 'safety-sticker-4', title: '대피 스티커', type: 'sticker' },
    steps: [
      {
        id: 'safety-4-step-1',
        type: 'choice',
        instructionText: '불이 나면 먼저 무엇을 해야 할까요?',
        choices: [
          { id: 'exit', label: '밖으로 나가요' },
          { id: 'hide', label: '숨어요' },
          { id: 'toy', label: '장난감을 챙겨요' },
        ],
        correctChoiceId: 'exit',
        hintText: '몸을 안전한 곳으로 옮기는 것이 먼저예요.',
        successMessage: '대피 방법을 잘 골랐어!',
      },
    ],
  },
  {
    id: 'safety-5',
    categoryId: 'safety',
    title: '개인정보를 지켜요',
    level: 5,
    order: 5,
    introduction: '내 이름과 전화번호를 안전하게 지키는 방법을 배워요.',
    reward: { id: 'safety-badge-5', title: '안전 사막 배지', type: 'badge' },
    steps: [
      {
        id: 'safety-5-step-1',
        type: 'choice',
        instructionText: '모르는 사람이 전화번호를 물어봐요. 어떻게 할까요?',
        choices: [
          { id: 'ask-guardian', label: '보호자에게 물어봐요' },
          { id: 'tell', label: '바로 말해요' },
          { id: 'write', label: '종이에 써줘요' },
        ],
        correctChoiceId: 'ask-guardian',
        hintText: '중요한 정보는 보호자와 함께 이야기해요.',
        successMessage: '소중한 정보를 잘 지켰어!',
      },
    ],
  },
];

export const sampleProgress: QuestProgress[] = [
  { profileId: DEFAULT_PROFILE_ID, questId: 'math-1', status: 'completed', attempts: 1 },
  { profileId: DEFAULT_PROFILE_ID, questId: 'language-1', status: 'inProgress', attempts: 3 },
  { profileId: DEFAULT_PROFILE_ID, questId: 'social-1', status: 'notStarted', attempts: 0 },
  { profileId: DEFAULT_PROFILE_ID, questId: 'safety-1', status: 'notStarted', attempts: 0 },
];
